from gym_soccer.envs.soccer_env import SoccerEnv
from gym_soccer.envs.soccer_empty_goal import SoccerEmptyGoalEnv
from gym_soccer.envs.soccer_against_keeper import SoccerAgainstKeeperEnv
from gym_soccer.envs.soccer_against_static_keeper import SoccerAgainstStaticEnv
